/**
 * Sacred Circuits structured data
 *
 * This module exports the structured circuit data consumed by the Sacred Circuits
 * UI. The canonical human-readable source for each circuit lives alongside this
 * file as Markdown:
 *
 *   - jyotirlingas.md
 *   - shakti-peethas.md
 *   - divya-desams.md
 *   - char-dhams.md
 *
 * Do not edit the JS objects directly for content changes; update the Markdown
 * files and regenerate this module if a full parser is introduced later.
 */

export const CIRCUITS = [
  {id:"jyotirlingas",name:"Dvādasha Jyotirlinga Circuit",shortName:"12 Jyotirlingas",sk:"ज्योतिर्लिङ्ग",deity:"Shiva",count:12,hue:350,
    essence:"Twelve pillars of primordial fire where Śiva blazes as self-revealed light — swayambhu lingas that erupted from the earth without human hands, radiating the absolute consciousness that pierces time, death, and the illusion of separateness. To stand before each is to stand before the column of light that has no beginning and no end.",
    significance:"When Brahma and Vishnu contested supremacy, Shiva manifested as an infinite column of fire — the Jyotirlinga. Brahma lied about reaching its top; Vishnu surrendered. Shiva cursed Brahma and blessed Vishnu, establishing the supreme nature of conscious surrender. The twelve Jyotirlingas mark the twelve points where this cosmic fire touched the earth and remains eternally accessible. The Shiva Purana declares that even the sight of these lingas burns accumulated karma across seven lifetimes. Each linga is swayambhu — self-arisen — not made by hands but condensed from the divine will of Maheshvara. Completing the circuit is described as equal to completing a thousand Ashwamedha yagnas.",
    temples:[
      {n:"Somnath",loc:"Prabhāsa Pātan, Saurashtra, Gujarat",note:"First & most ancient Jyotirlinga · Faces the Arabian Sea · Rebuilt 17 times after invasions · Moon (Chandra) installed the original · Massive 49m spire rebuilt in 1951 under Sardar Patel · Darshan: 6 AM–9:30 PM"},
      {n:"Mallikārjuna",loc:"Srisailam, Nandyal district, Andhra Pradesh",note:"Second Jyotirlinga · Also a Shakti Peetha (neck of Sati) · Deep gorge of Krishna River · 2,000-year-old temple · Shiva and Parvati dwell as Mallikarjuna and Bhramaramba · Accessible by ropeway · Open 5:30 AM–10 PM"},
      {n:"Mahākāleshwar",loc:"Ujjain, Madhya Pradesh",note:"Third Jyotirlinga · Only south-facing (Dakshinamukhi) Jyotirlinga · Lord of Time and Death · Famous Bhasma Aarti at 4 AM uses ash from cremation grounds · Temple has five floors · City of Kumbh Mela every 12 years · Darshan 4 AM–11 PM"},
      {n:"Omkāreshwar",loc:"Mandhata Island (Shivapuri), Khandwa district, MP",note:"Fourth Jyotirlinga · Island shaped like the sacred syllable Aum when seen from air · Two lingas — Omkareshwar and Mamleshwar — on same island · Narmada encircles the island · 1,000-year-old Paramara dynasty temple · Rope bridge + boat access"},
      {n:"Kedārnāth",loc:"Rudraprayag district, Uttarakhand — 3,583m altitude",note:"Fifth Jyotirlinga · Highest Jyotirlinga in the Himalayas · Part of Pancha Kedar · Linga is a natural hump-shaped rock (Shiva as a bull) · 16km trek from Gaurikund · Open only May–November · Uttarakhand glacier backdrop · One of the 64 Shaiva sites of liberation"},
      {n:"Bhīmāshankar",loc:"Sahyadri hills, Pune district, Maharashtra — 3,250ft",note:"Sixth Jyotirlinga · Source of the Bhima River · Dense Sahyadri forest sanctuary with rare wildlife · Shiva slew the demon Bhima here · Wildlife Sanctuary surrounds the temple · Trek or road access from Pune (110km) · Pre-dawn aarti at 4:30 AM"},
      {n:"Kāshi Vishvanāth",loc:"Dashashvamedha Ghat area, Varanasi, Uttar Pradesh",note:"Seventh Jyotirlinga · Lord of the Universe (Vishveshvara) · Varanasi is the city where Shiva whispers the Taraka mantra into the ear of the dying — guaranteeing liberation · New Corridor (2022) restored ancient views · Ganges flows north here — rarest cosmic alignment · Darshan 3 AM–11 PM · Shringara Aarti at sunrise is transcendent"},
      {n:"Tryambakeshwar",loc:"Nashik, Maharashtra — on Brahmagiri mountain",note:"Eighth Jyotirlinga · Three-faced linga representing Brahma, Vishnu, Shiva · Source of the sacred Godavari River · Kumbh Mela held every 12 years at Nashik · Panchavati (Rama's exile site) is 30km away · Ancient black stone linga barely visible in silver crown · Non-Hindus have limited sanctum access"},
      {n:"Vaidyanāth (Baidyanath)",loc:"Deoghar, Santhal Pargana, Jharkhand",note:"Ninth Jyotirlinga · The Healing God (Vaidya = physician) · Ravana installed this linga after severe penance · Also a Shakti Peetha · Shravan month: millions carry sacred Gangajal from Sultanganj (108km) on foot — world's largest annual pilgrimage walk · 22 temples in the complex · Open 4 AM–3:30 PM, 6 PM–9 PM"},
      {n:"Nāgeshwar",loc:"Dwarka coast, Saurashtra, Gujarat",note:"Tenth Jyotirlinga · Lord of Serpents (Naga = serpent) · Massive 25m Shiva statue outside · Located 17km from Dwarka (Char Dham) — visit both in one day · Ancient mythology: Shiva appeared here to free devotee Supriya from demon Daruka · Also called Nagnathaswami"},
      {n:"Rāmanathaswamy",loc:"Rameswaram Island, Tamil Nadu — Indian Ocean junction",note:"Eleventh Jyotirlinga · Also a Char Dham site · Sri Rama installed this linga to expiate Brahmahatya after killing Ravana · Longest temple corridor in the world — 1,220 metres · 22 sacred teerthams (wells) in the complex — each with unique mineral composition · Linked to mainland by Pamban Bridge · Also revered by Muslims and Christians"},
      {n:"Ghrishneshwar",loc:"Verul, Aurangabad district, Maharashtra — near Ellora",note:"Twelfth and final Jyotirlinga · Goddess Ghushma's devotion moved Shiva to appear here as the Compassionate Lord · Situated 1km from Ellora Caves (UNESCO World Heritage) · 18th-century temple rebuilt by Ahilyabai Holkar · Red-stone architecture · Completes the sacred circuit — arriving here signals full completion of the Dvādasha yatra"},
    ],
    pacing:[
      {days:30,label:"Complete Sacred Circuit",desc:"The traditional 30-day pilgrimage traversing all 12 Jyotirlingas in the sequence prescribed by the Shiva Purana. Begin at Somnath (Gujarat) at the Arabian Sea at dawn. Move south to Rameswaram, then north through the Deccan, climb to Kedarnath, descend through the Gangetic plains, and close at Ghrishneshwar beside Ellora. Budget ₹60,000–₹1.2 lakh. Includes time for overnight rituals at Kashi and the Kedarnath trek. Best: October–November (Kedarnath still open, South comfortable)."},
      {days:18,label:"Dedicated Pilgrim",desc:"An 18-day focused circuit combining regional clusters with efficient routing. Four geographic hubs: Gujarat cluster (Somnath, Nageshwar, Omkareshwar), Maharashtra cluster (Tryambakeshwar, Bhimashankar, Ghrishneshwar), South (Mallikarjuna, Rameswaram), North (Varanasi, Ujjain, Vaidyanath, Kedarnath). Fly between clusters. Budget ₹45,000–₹80,000. Requires pre-booked trains/flights. Kedarnath needs 2 dedicated days for trek."},
      {days:10,label:"Essential Journey",desc:"A spiritually meaningful 10-day sprint covering the most accessible Jyotirlingas by air and train: Day 1–2 Varanasi (Kashi Vishvanath), Day 3 Ujjain (Mahakaleshwar), Day 4–5 Somnath + Nageshwar (Gujarat), Day 6–7 Nashik (Tryambakeshwar), Day 8–9 Rameswaram, Day 10 Omkareshwar. Skip Kedarnath (seasonal) and Vaidyanath (remote). Budget ₹25,000–₹45,000."},
    ],
    season:"Oct–Mar best overall · Sāvan (Jul–Aug) for spiritual intensity at Varanasi though very crowded · Kedarnath open only May–Nov · Mahashivaratri (Feb/Mar) transforms every Jyotirlinga site · Avoid Shravan Mondays at Varanasi and Deoghar — millions on foot",
    bestFor:"Shaiva devotees · Maha Shivaratri pilgrims · Seekers of moksha and liberation · Pancha Kedar mountaineers · Philosophers of Advaita Vedanta · Those seeking healing (Vaidyanath) · Shiva-bhaktas undertaking lifetime pilgrimage",
    tips:[
      "Begin at Somnath at sunrise facing the Arabian Sea — there is no land between you and the South Pole. Stand in that vastness and chant the Mahamrityunjaya Mantra before entering.",
      "Kashi Vishvanath at 3 AM: arrive at Dashashvamedha Ghat, watch the Ganga Aarti at dusk the night before, then queue for the pre-dawn darshan. The Bhasma Aarti (4 AM, by advance booking) is one of the most sacred rituals in India.",
      "Kedarnath: begin 3 months of walking 5km daily as physical preparation. The 16km trek from Gaurikund (1,982m) to Kedarnath (3,583m) gains 1,600m altitude. Hire a pony or palanquin only if medically needed — the walk itself is the tapasya.",
      "Mahakala Ujjain Bhasma Aarti: the ash (bhasma) from actual cremation grounds is applied to the linga at 4 AM — attendance requires online registration. This darshan is worth a 3-day Ujjain stay alone.",
      "Omkareshwar: take the parikrama (circumambulation) of the island — 7km walk that passes through fields, ghats, and ancient temples. The experience of seeing the Aum-shaped island from the bridge at sunset is unforgettable.",
      "Vaidyanath / Deoghar in Shravan month: if you undertake the Kanwar Yatra (carrying Gangajal from Sultanganj 108km on foot), you will walk alongside 30 million pilgrims. The spiritual electricity is unlike anything else on earth — but book accommodation 3 months ahead.",
      "Rameswaram: bathe in each of the 22 teerthams (wells) in the prescribed sequence before entering the inner sanctum. Each teerth has a different mineral taste. The priest at each will pour the water over you. Allow 3 hours for this ritual.",
      "Recite the Dvādasha Jyotirlinga Stotram at each temple — the 12-verse hymn naming all lingas. Singing it at each site creates an energetic circuit that links all 12 and amplifies the darshan of each subsequent Jyotirlinga.",
      "Simhastha Kumbh at Ujjain (every 12 years, next 2028): if your circuit coincides, restructure everything to be in Ujjain during the main bathing date — it is a once-in-a-lifetime multiplication of merit.",
      "Ghrishneshwar: arrive last, after completing all other 11. Perform a final abhishekam and sit in contemplation in the courtyard — the feeling of completion is unlike anything a mere tourist could understand.",
    ],
    stotram:"Saurāṣhṭre Somanāthaṃ ca Śrīsaile Mallikārjunam\nUjjayinyāṃ Mahākālaṃ Oṃkāre Parameśhvaram\nKedāre Kedarīśhaṃ ca Ḍākinī Bhīmashaṅkaram\nVārāṇasyāṃ tu Vishveśhaṃ Tryambake Gautamītaṭe\nHimālaye tu Vaidyānātham Āmrājādye tu Nāgeshvaram\nCitābhoome tu Rāmesham Śhivalaye Ghrishneshvaram\nDvādaśhaitāni nāmāni prātarutthāya yaḥ paṭhet\nSarvapāpavinirmukto Śhivaloke mahīyate"},
  {id:"shakti_peethas",name:"Shakti Peetha Circuit",shortName:"51 Shakti Peethas",sk:"शक्तिपीठ",deity:"Devi",count:51,hue:280,
    essence:"Fifty-one seats of power where the body of Satī fell — each fragment became a vortex of divine feminine energy that still pulses across the subcontinent. Together they form the living body of the Goddess herself, distributed across Bhārata so that no corner of the sacred land remains without her presence. To visit them is to walk inside the body of the Mother.",
    significance:"The myth: Sati's father Daksha insulted her husband Shiva by excluding him from the great Yajna. Sati entered the sacred fire and died. Shiva, inconsolable, wandered the cosmos carrying her body. To release him from grief, Vishnu used the Sudarshana Chakra to sever the body into 51 (some texts say 108) pieces. Wherever a fragment fell, the earth became a Shakti Peetha — a throne of the Goddess. Each peetha has a specific presiding goddess name, a specific body-part of Sati, and a Bhairava (Shiva) guardian. The Peethas span from Kamakhya in Assam to Kanyakumari at the southern tip, from Dwarka on the Arabian Sea to Tarapith in Bengal. Together they form the complete cosmic body of Shakti — every devotee visiting all 51 symbolically reconstitutes the wholeness of the Divine Mother. The Tantric tradition holds the Peethas as the highest concentration of Shakti energy on earth.",
    temples:[
      {n:"Kamakhya",loc:"Nilachal Hill, Guwahati, Assam",note:"Supreme Shakti Peetha — yoni (womb) of Sati fell here · No idol — a natural stone yoni-kund filled with sacred spring · Ambubachi Mela (June): Goddess 'menstruates' — temple closed 3 days, then thousands receive the red cloth · Greatest Tantric seat in India · Umananda island temple on Brahmaputra nearby · Bhairava: Umananda"},
      {n:"Kalighat",loc:"South Kolkata, West Bengal",note:"Right toes of Sati · 10-armed Kali in gold · Ramakrishna Paramahamsa attained samadhi here · Adjacent to the burning ghats of Adi Ganga · One of the 4 Adi Peethas (original seats) · The fish-shaped tongue of Kali is a highlight · Ancient 200-year-old temple in its current form · Bhairava: Nakulesh"},
      {n:"Jwālā Devī",loc:"Kangra district, Himachal Pradesh",note:"Nine eternal blue flames emerge from rock without fuel — pure Shakti fire · Tongue of Sati fell here · Akbar tried to extinguish the flames with water — failed and offered a golden umbrella in awe · Natural gas seeps are geologically unique · Himachal hilltop with stunning views · Bhairava: Unmatta · Darshan 5 AM–8 PM"},
      {n:"Vaishnodevi",loc:"Trikuta Hills, Reasi, J&K — 5,200ft altitude",note:"Vaishno Devi (right arm) · Most visited peetha — 8 million pilgrims annually · 13km trek from Katra (helicopter available) · Three natural pindiis (rock formations) represent Maha Kali, Maha Lakshmi, Maha Saraswati · Bhairon temple visit after peetha darshan is mandatory — 3km return trek · Bhairava: Bhairon Nath"},
      {n:"Nainā Devī",loc:"Bilaspur district, Himachal Pradesh — hilltop shrine",note:"Eyes of Sati fell here · Ancient shrine with spectacular views of Gobind Sagar Lake · Ropeway from base · The eyes are represented by two silver eyes in the sanctum · Chintpurni peetha (feet of Sati) is 65km away — often visited together · Navratri draws hundreds of thousands · Bhairava: Kruddha"},
      {n:"Kanyākumāri (Śhri Bhagavatī)",loc:"Cape Comorin, Tamil Nadu — India's southernmost tip",note:"Right shoulder of Sati · Where Arabian Sea, Indian Ocean, and Bay of Bengal meet · Goddess is unmarried — still awaiting Shiva · Viveka Ananda Rock Memorial 200m offshore · Sunrise over three oceans from the temple steps is a transformative sight · Bhairava: Nimisha · Sunset and sunrise are both special here"},
      {n:"Mahālakshmī (Ambabai)",loc:"Kolhapur, Maharashtra",note:"Eyes of Sati fell here (some texts: right breast) · One of 18 Mahashakti Peethas and Shakta equivalent of the 12 Jyotirlingas in importance · Magnificent black stone idol · The sun's rays fall directly on the idol during two specific days of the year · Satvic seat — no blood sacrifice · Bhairava: Kruddha Bhairava"},
      {n:"Tulajā Bhavāni",loc:"Tuljapur, Osmanabad, Maharashtra",note:"Right shoulder or feet (texts vary) · Kuldevi (clan goddess) of the Maratha clan · Chhatrapati Shivaji's protective deity — he received the sacred sword Bhavani from her · Massive complex atop a hill · Navratri is extraordinary here — 9-day celebration involving the entire region · Bhairava: Kala Bhairava"},
      {n:"Mānasā Devī (Chanda Devi)",loc:"Mansa Devi Hill & Chanda Devi Hill, Haridwar, Uttarakhand",note:"Mind of Sati · Two separate peethas near Haridwar — both visited as a pair · Mansa Devi ropeway has stunning Ganga views · Har Ki Pauri Ganga Aarti at dusk below completes the visit · Navratri: massive crowds · Bhairava: Kapalish Bhairava"},
      {n:"Tarapith",loc:"Birbhum district, West Bengal — beside the Dwarka river",note:"Third eye of Sati · Cremation ground (Mahāśmaśāna) adjacent to the temple — still active · Tantric seat of Tara (fierce form of Durga) · Bamakhyapa, the great 19th-century Tantric saint, attained liberation here · The idol is mother Tara nursing a child Shiva · Jackals and vultures sacred here · Not for the faint-hearted · Bhairava: Tara Bhairava"},
      {n:"Dakshina Kālī (Dakshineshwar)",loc:"Dakshineswar, Kolkata, West Bengal",note:"Toes of Sati · Sri Ramakrishna Paramahamsa was the priest here for 30 years and attained God-realization · 12 Shiva temples surrounding the main shrine · Vivekananda visited daily as a youth · On the east bank of Ganga · Accessible by river ferry from Belur Math · The garden and riverside atmosphere are extraordinary"},
      {n:"Biraja (Bimala)",loc:"Jajpur, Odisha",note:"Navel of Sati · One of 4 Adi Peethas · Located inside the Jagannath Puri temple complex — only peetha inside a Vaishnava temple · Bimala Devi receives offering of fish and meat which is then consecrated into prasad for Jagannath · Unique theological synthesis of Shakta and Vaishnava traditions"},
      {n:"Daksha Prajāpati (Sati Kund)",loc:"Kankhal, Haridwar, Uttarakhand",note:"Where Sati immolated herself in Daksha's Yajna fire · This is the origin-point of the entire Shakti Peetha tradition · Ancient Daksha Mahadev temple · On the banks of Ganga · Sacred but often overlooked by pilgrims focused on Haridwar's main ghats · Historically, this is where the story begins"},
      {n:"Shārada Peetha",loc:"Sharada, PoK (now inaccessible from India)",note:"Right hand · One of the most sacred and now tragically inaccessible peethas · The legendary Shārada University near Kashmir was the Oxford of ancient India · The site draws profound longing among pilgrims · Proxy worship performed at surrogate temples in Kashmir · A peetha that carries the grief of partition"},
    ],
    pacing:[
      {days:90,label:"Complete Pilgrimage",desc:"The full 90-day circuit of all 51 Shakti Peethas spans India, Nepal (Guhyeshwari, Ugratara, Manakamana), and Bangladesh (Jashoreshwari, Sugandha). Five geographic arcs: North Himalayan (Vaishno Devi, Jwala Devi, Naina Devi, Mansa Devi — 15 days), East Bengali Arc (Kamakhya, Kalighat, Tarapith, Biraja — 20 days), West Deccan (Mahalakshmi, Tuljapur, Mahur, Aundha — 15 days), South (Kanyakumari, Madurai, Chamundi — 15 days), Central (Prayagraj, Varanasi, Vindhyavasini — 10 days) plus 15 days travel. Budget ₹1.5–₹2.5 lakh. Arrange Bangladesh and Nepal peethas with advance visa planning."},
      {days:45,label:"18 Mahāshakti Peethas",desc:"The 18 Mahashakti Peethas (Ashtadasha Peethas) are the highest-ranked among the 51 — the spines of the Goddess's cosmic body. These include: Kamakhya, Kalighat, Jwala Devi, Vaishno Devi, Mahalakshmi (Kolhapur), Kanyakumari, Vindhyavasini (Mirzapur), Ambaji (Gujarat), Chamundeshwari (Mysore), Bhramaramba (Srisailam), Hinglaj (Balochistan — by proxy), Mahur (Maharashtra), and others. 45 days, 4 clusters, 2 flights. Budget ₹70,000–₹1.2 lakh."},
      {days:21,label:"Regional Arc — Your Choice",desc:"21-day immersion in one geographic arc of Shakti Peethas. North Arc: Vaishno Devi → Jwala Devi → Naina Devi → Mansa Devi → Chintpurni — all in Himachal and J&K. East Arc: Kamakhya → Kalighat → Tarapith → Bakreshwar → Biraja. West Arc: Mahalakshmi Kolhapur → Tuljapur → Mahur → Ambaji. South Arc: Kanyakumari → Madurai Meenakshi → Chamundeshwari. Each arc is complete, spiritually coherent, and deeply rewarding."},
    ],
    season:"Oct–Mar best overall · Navratri (Ashvin: Sep/Oct, Chaitra: Mar/Apr) — both Navratris are peak spiritual time at all peethas · Ambubachi Mela at Kamakhya (June): extraordinary but very crowded · Avoid monsoon at Himalayan peethas · Shravan (Jul–Aug) at Vaishno Devi is sacred but overcrowded · Diwali at Kalighat is unique",
    bestFor:"Shakta devotees and Devi worshippers · Tantric practitioners and initiates · Navratri pilgrims · Those seeking Devi's protective grace (kavacha) · Women pilgrims (Devi peethas are especially women-honoring) · Artists, poets, and creators seeking the Goddess of creation · Those in grief — Devi as mother is the most accessible form of the divine",
    tips:[
      "Kamakhya during Ambubachi Mela (June 21–25): the Goddess is in her period — the temple closes for 3 days, then opens to give the red cloth (rakta vastra). Sitting in the courtyard during these 3 days in silence while thousands of Tantrics meditate is an experience with no parallel in the world.",
      "Vaishno Devi: leave Katra by 2 AM to arrive at Bhawan for sunrise darshan. The atmosphere inside the cave at dawn — when natural light filters in and the three pindis glow — is the closest thing to seeing the Goddess face to face. Return via the Bhairon temple — tradition holds that the pilgrimage is incomplete without Bhairon darshan.",
      "Tarapith: if you are prepared spiritually, visit at night. The cremation ground adjacent to the temple is one of the most powerful Tantric spaces in India. Bamakhyapa's samadhi is beside the Dwarka river. The ash and bones are not morbid — they are the dissolution of ego that the Goddess requires.",
      "Jwala Devi: stand before the nine eternal flames and understand that fire without fuel is the Goddess herself — pure consciousness without cause. Pour ghee into the flames and observe how they accept and transcend. Even Akbar was humbled here.",
      "Kalighat at 4 AM: join the antara darshan (inner darshan) — a 10-minute experience of seeing the 10-armed Kali at very close proximity. The wooden tongue with silver eyes and golden arms in the red oil-lamp light is something the mind can never un-see.",
      "Learn the Mahishasura Mardini Stotram before the circuit — 21 verses by Adi Shankaracharya describing the Goddess in her victory over the buffalo demon. Reciting it at each peetha links your mind to the Goddess in her most powerful aspect.",
      "At Kanyakumari, wake before sunrise and position yourself at the temple steps facing east. On Vaikuntha Ekadashi and Shivratri, the sunrise and the setting moon align with the idol's eyes — the single most celebrated optical miracle in South Indian Devi worship.",
      "The 18 Mahashakti Peethas include peethas in current Pakistan (Hinglaj, Balochistan) and Bangladesh (Jashoreshwari). Arrange proxy puja at local surrogate temples and acknowledge these geopolitically inaccessible sacred sites in your prayers — this acknowledgement itself is considered auspicious.",
      "Biraja Peetha (Jajpur, Odisha) is inside the Jagannath Puri complex — the only Shakti Peetha inside a Vaishnava temple. What Jagannath receives as prasad is first offered to Bimala Devi. This theological unity of Shakta and Vaishnava is one of India's most profound spiritual achievements.",
      "If you visit during Navratri, fast on the Ashtami (8th day) and break it only with prasad from the Devi peetha. The fast throughout the 9 nights while moving between peethas is one of the most transformative spiritual practices available to a pilgrim.",
    ],
    stotram:"Mahālakshmī cha Kāmākhyā Tullā Caṇḍī Sarasvatī\nDurgā Kātyāyanī Gauri Revatī Lalitā Śhivā\nMaheshvarī Mahāmāyā Bhavānī Bhairavī tathā\nViṣhṇumāyā Śhivādūtī Sarvamaṅgalā tathā ca\nEtāni Śhakti pīṭhāni nāmāni prātar utthāya\nYaḥ paṭhet sarvapāpebhyo mucyate nātra saṃśhayaḥ"},
  {id:"divya_desams",name:"Divya Desam Circuit",shortName:"108 Divya Desams",sk:"दिव्यदेशम्",deity:"Vishnu",count:108,hue:215,
    essence:"One hundred and eight abodes where Vishnu dwells in forms perceived and sung by the twelve Alvar poet-saints — every verse of the Nalayira Divya Prabandham is a living key unlocking the deepest gates of these sacred precincts. The Alvars did not describe temples — they described God, and the temples grew around their vision.",
    significance:"Between 600 and 900 CE, twelve Tamil poet-saints — the Alvars — entered states of divine absorption before 108 Vishnu temples and poured out the Nalayira Divya Prabandham: 4,000 Tamil verses of such concentrated devotion that Vaishnavism in South India was forever transformed. Nammalvar alone composed 1,102 verses. Andal composed the Thiruppavai (30 verses) which is sung daily at every Divya Desam. The tradition teaches that the Alvars were liberated souls sent by Vishnu himself to sing his glories and show humanity the path of prapatti (total surrender). Ramanuja (11th century) compiled and systematized the Prabandham, which now has equal status with the Sanskrit Vedas in Sri Vaishnava tradition — called the 'Dravida Veda.' Temple #108 is Thirupparamapadham — Vaikuntham itself, the transcendent abode that no living pilgrim can physically reach but which every completed circuit symbolically enters.",
    temples:[
      {n:"Tirumala Venkateswara",loc:"Tirumala hills, Tirupati, Andhra Pradesh — 853m",note:"Desam #1 in common sequence · Wealthiest religious institution on Earth (₹50,000 crore+ endowment) · 50,000–100,000 pilgrims daily · Seven hills (Saptagiri) as the serpent Adishesha's hoods · The idol's third eye reveals itself only to the deserving · Laddu prasadam is GI-tagged · Book special darshan (₹300) 45+ days online · Tirupati airport nearby"},
      {n:"Srirangam Ranganātha",loc:"Srirangam Island, Tiruchirappalli, Tamil Nadu",note:"The greatest Divya Desam · Largest functioning temple complex in the world (156 acres, 21 gopurams) · Vishnu reclines on Adishesha on the Kaveri island · 7 enclosures (prakarams) — outer ones allow all · Inner sanctum: Vishnu asleep in eternal yoga nidra · Vaikunta Ekadashi: Paramapada Vasal (Gateway to Vaikuntham) opens once per year at midnight · Ramanujacharya's body preserved here"},
      {n:"Badrinath (Badrī Nārāyaṇa)",loc:"Chamoli, Uttarakhand — 3,133m altitude",note:"North India's only Divya Desam · Char Dham site · Vishnu meditates here in the form of a black stone Shaligrama under Badri trees · Adi Shankaracharya established the puja system here in 8th century · Nar-Narayana peaks behind the temple · Open May–November · First darshan of the season (Kapat Utsav) is sacred beyond description"},
      {n:"Dwaraka (Dvarakā Nārāyaṇa)",loc:"Dwarka, Gujarat — on Arabian Sea",note:"Char Dham and Divya Desam · Original Dwaraka is submerged (marine archaeology confirms structures at 40m depth) · Krishna's capital · 72-pillar temple with 5-story tower visible from the sea · Bet Dwarka island 30km away has the original dwelling of Krishna · Gomti River joins sea here — sacred bath prescribed · Also Nageshwar Jyotirlinga 17km away"},
      {n:"Varadarāja Perumal",loc:"Kanchipuram, Tamil Nadu",note:"City of a thousand temples · Sri Vaishnava capital · Varadaraja ('giver of boons') Vishnu on an elephant (Hastagiri) · 100-pillar mandapam has 14th-century Hoysala sculpture · The gold and silver idols alternate in their appearance every 40 years — visible only during special festivals · Adjacent to Kamakshi Amman (Shakti Peetha)"},
      {n:"Padmanābhaswamy",loc:"Thiruvananthapuram, Kerala",note:"Vishnu reclining on Ananta Shesha spanning three chambers · Supreme Court order (2011) revealed six vaults worth estimated ₹1.2 lakh crore · Vault B remains sealed — considered by some as protected by divine serpent Naga · Only Hindus allowed inside · Entry requires traditional Kerala dress (dhoti for men, saree/mundu-blouse for women) · One of the 108 Divya Desams and wealthiest in Kerala"},
      {n:"Guruvāyurappan",loc:"Guruvayur, Thrissur, Kerala",note:"'Dwarka of the South' · Krishna as a child (Bala Krishna / Unnikrishnan) is the presiding deity · The black Vishnu idol brought by Brahma was installed by Guru (Brihaspati) and Vayu (wind) — hence Guruvayur · 60+ elephants live in the temple's elephant sanctuary (Punnathur Kotta) · Devotees donate elephants — temple owns most elephants in the world · No cameras inside · Prasad: a specific sweet rice pudding unlike any other"},
      {n:"Muktināth",loc:"Mustang district, Nepal — 3,710m altitude",note:"Only Divya Desam outside India · 108 sacred springs flow from 108 stone waterspouts around the sanctum · Natural eternal flame burns from a rock · Avalokitesvara Buddhist shrine adjacent — unique Hindu-Buddhist sacred coexistence · Accessible from Pokhara via Jomsom (flight + road/trek) · Pilgrimage season: May–October · Altitude sickness preparation essential"},
      {n:"Ayodhyā (Rāma)",loc:"Ayodhya, Uttar Pradesh — on Sarayu River",note:"Birthplace of Rama (Ram Lalla) · New Ram Mandir consecrated January 2024 — historic moment · Sarayu River ghats for ritual bath prescribed before darshan · 14 Kosa Parikrama of the entire city is the traditional circuit · Kanak Bhawan (palace where Sita and Rama lived) · Hanuman Garhi temple guards the way · Valmiki Ramayan was composed here · City of 7 sacred forests"},
      {n:"Mathurā & Vrindāvan",loc:"Mathura and Vrindavan, Uttar Pradesh — on Yamuna",note:"Birthplace of Krishna · Keshavarāya temple at the exact birthspot (Krishna Janmabhoomi) · Vrindavan: 5,000 temples in a 10km radius — Banke Bihari, Iskcon, Prem Mandir, Radha Raman · Govardhan Puja (parikrama of Govardhan Hill — 21km circumambulation) · Yamuna: sacred bath before visiting Mathura · Braj region (40km radius) has 84 forests (vans) associated with Krishna's childhood · Holi in Braj — 7-day celebration across different villages — is life-altering"},
      {n:"Srivilliputtūr Āṇḍāl",loc:"Srivilliputtur, Virudhunagar district, Tamil Nadu",note:"Temple of Andal — the only female Alvar saint · The 72m gopuram visible for miles · Andal composed the Thiruppavai (30 verses) and the Nachiyar Tirumozhi · The entire story of Andal's divine marriage to Vishnu happened here · Andal was found as an infant in the temple garden · Her image stands beside Ranganatha everywhere in Sri Vaishnava temples · Tamil Nadu government's official emblem is this gopuram"},
      {n:"Tirukkuṛungudi Nambī",loc:"Tirunelveli district, Tamil Nadu",note:"Vishnu stands facing south (extremely rare — south is the direction of death, conquered by Vishnu here) · One of the 32 standing Vishnu forms in the Divya Desam canon · Close to Kanyakumari · Nammalvar sang several verses here · Surrounded by beautiful paddy fields of southern Tamil Nadu · Less visited — more peaceful than the major Desams · Pre-dawn aarti at 5:30 AM is particularly atmospheric"},
      {n:"Tiru Nāṅgūr group",loc:"Nagapattinam district, Tamil Nadu — Cauvery delta",note:"Eleven small Divya Desams clustered in the Nangur area — all visitable in one day by car · Tiny village temples with extraordinary Chola-period sculpture · The Nangur group represents the 'hidden treasury' of the Divya Desam circuit — pilgrims who complete these feel they have found the secret heart of the tradition · Paddy fields, coconut groves, and ancient stone corridors"},
    ],
    pacing:[
      {days:60,label:"Complete Circuit (108 Desams)",desc:"The full circuit visits all 108 Divya Desams in the canonical Alvar order. 84 are in Tamil Nadu (concentrated in Kaveri delta and Pallava/Chola heartland), 11 in Kerala, 2 in UP (Mathura, Ayodhya), 1 in Gujarat (Dwarka), 1 in Uttarakhand (Badrinath), 1 in Nepal (Muktinath), 1 in Andhra (Tirumala), and 1 transcendent (Vaikuntham). 60-day plan: Tamil Nadu in 30 days (rent a car, base in Kumbakonam/Trichy/Madurai), Kerala in 8 days, North India + Badrinath in 12 days, Andhra in 4 days, Nepal in 6 days. Budget ₹1.5–₹2.5 lakh. Carry Divya Prabandham booklet to recite Pasuram at each."},
      {days:30,label:"Tamil Nadu Deep Immersion",desc:"30 days, 84 Tamil Nadu Divya Desams — the heart of the Alvar tradition. Base cities: Kanchipuram (north cluster, 5 desams), Chidambaram (east cluster), Kumbakonam (Kaveri delta — 40+ desams within 60km radius), Trichy/Srirangam (central), Madurai (south cluster), Tirunelveli (far south cluster). Rent a self-drive car from Chennai. The Kaveri delta cluster alone has 40 Desams within a 50km radius — this is the spiritual heartland of Sri Vaishnavism. Stay in temple towns and wake at 4 AM for pre-dawn aarti."},
      {days:15,label:"Essential 12 Desams",desc:"15-day curated journey of the 12 spiritually paramount Desams: Tirumala (2 days, Andhra), Srirangam (2 days, Tamil Nadu), Kanchipuram Varadaraja (1 day), Thiruvananthapuram Padmanabha (1 day), Guruvayur (1 day), Badrinath (3 days including travel and trek, Uttarakhand), Dwarka (1 day, Gujarat), Mathura-Vrindavan (2 days, UP), Ayodhya (1 day). Connects all four directions of India. Budget ₹35,000–₹60,000. Fly between clusters. This itinerary alone covers the most celebrated forms of Vishnu from Ananta Shayana to Bala Krishna."},
    ],
    season:"Nov–Mar for Tamil Nadu and Kerala (pleasant, festivals) · May–Jun for Badrinath and Muktinath · Vaikunta Ekadashi (Dec/Jan) at Srirangam — once-per-year cosmic event · Thai Pongal (Jan) at Tamil Desams — extremely auspicious · Karthigai Deepam (Nov) for northern Tamil Nadu · Brahmotsavam at Tirumala (Sep) — 9-day festival, world's largest religious gathering",
    bestFor:"Sri Vaishnava devotees and initiates · Bhakti yoga practitioners · Students of Tamil Sangam literature · Temple architecture enthusiasts (Chola, Pallava, Hoysala masterpieces) · Those seeking prapatti (total surrender to Vishnu) · Devotees of Rama, Krishna, and the various forms of Vishnu · Serious pilgrims who want depth over breadth",
    tips:[
      "Recite the Thiruppavai (Andal's 30 verses) in its entirety before your circuit begins — each verse was composed before a specific Desam and becomes intelligible only when you stand before it. Learn at minimum Pasuram 1, 11, and 30.",
      "At Tirumala: book Special Entry Darshan (SED, ₹300) online at ttdsevaonline.com at least 45 days ahead. Arrive 1 hour before your slot. Alternatively, join the Sarva Darshan (free queue) with true surrender — average wait 6–8 hours. The Lord's choice of who enters easily is itself a teaching.",
      "Srirangam on Vaikunta Ekadashi (Dec/Jan Ekadashi): the Paramapada Vasal (Gate of Vaikuntham) opens at midnight. Stepping through it is symbolically stepping into the abode of Vishnu — liberation in a single step. Arrive 24 hours early and spend the night in the outer prakarams listening to Prabandham recitation.",
      "Undergo Panchasamskara (5-fold initiation into Sri Vaishnavism) from an authorized Acharya before the full circuit. The 5 rites — Tāpa (brand marks of conch and disc), Pundra (urdhva pundra tilak), Nāma (initiation of the mūla mantra), Mantra (Ashtakshara — Om Namo Narayanaya), and Yāga (daily worship) — transform pilgrimage from tourism into genuine spiritual practice.",
      "The Kaveri Delta cluster of 40+ Desams (within 50km of Kumbakonam) is the hidden heart of the circuit. Rent a car and driver for 4–5 days, staying in temple town dharmashalas. Villages like Thirucherai, Sirkazhi, Thirunangur, and Papanasam have extraordinary Chola-period architecture in almost no crowds.",
      "Guruvayur: witness the elephant procession (Thidambu Nritham) at 6 PM when the idol is placed on the lead elephant and paraded around the temple. The synchrony of elephants, musicians, and lamplight makes this one of the most visually overwhelming experiences in India.",
      "At Muktinath, pour water from all 108 stone waterspouts over yourself in sequence at dawn in the Himalayan cold. This is a ritual purification that the tradition says is equivalent to bathing in all sacred rivers of India simultaneously. The eternal flame from the rock — a natural gas seep — represents Vishnu's permanence.",
      "Padmanabhaswamy: wear traditional Kerala dress (men: mundu without shirt, women: saree). Entry is restricted to Hindus. Go at 3:30 AM for the first darshan of the day (Nirmalya Darsanam) when the idol is shown with previous day's flowers still on — this first glimpse in candlelight of the massive reclining Vishnu is something the mind cannot prepare for.",
      "The Alvar connection: at each temple, read the specific Pasuram (verse) composed for that Desam. The Arayar Sevai (performance of Prabandham verses through classical dance-drama) happens at Srirangam and Alwar Thirunagari — witnessing one is to understand how sacred literature becomes living devotion.",
      "Complete your circuit at Srirangam with the Sathumaurai (special offering) in which the Nalayira Divya Prabandham is recited in full. If you can arrange for a Vedaparayana and Prabandha Parayana simultaneously — the Tamil and Sanskrit traditions harmonizing — you will hear what Bharat's greatest spiritual synthesis sounds like.",
    ],
    stotram:"Śhrīman Nārāyaṇa caraṇau śharaṇaṃ prapadye\nŚhrīmate Nārāyaṇāya namaḥ · Śhrīmate Rāmānujāya namaḥ\nSarvān parityajya māmēkaṃ śharaṇaṃ vraja\nAhaṃ tvāṃ sarvapāpebhyo mokṣhayiṣhyāmi mā śhucaḥ\nKaṇṇinuṇ śirutthāmbu — Nammālvār\nThiruppāvai — Āṇḍāḷ: Mārgazhi Thingal Madhi Nirainda Nannāḷal"},
  {id:"char_dham",name:"Char Dham Circuit",shortName:"4 Sacred Dhams",sk:"चारधाम",deity:"Vishnu · Shiva · Devi",count:4,hue:42,
    essence:"Four corners of the sacred cosmos — Badrinath to the north where Vishnu meditates eternally, Puri to the east where Jagannath dances in ecstasy, Rameswaram to the south where Shiva blesses Ram's devotion, Dwarka to the west where Krishna ruled as king. Together they circumambulate the entire body of Bhārata, mapping the subcontinent as a single sacred mandala. To complete the four is to walk the entire body of India as a living deity.",
    significance:"Adi Shankaracharya (788–820 CE) walked barefoot across India four times, establishing four maths and four Dhams at the cardinal directions to unify the fractured spiritual geography of post-Buddhist India. His genius: each Dham enshrines a different deity (Vishnu, Jagannath, Shiva-as-Ram's-devotion, Krishna) yet together they dissolve sectarian boundaries. Each Dham corresponds to: one of his four maths (Jyotirmath, Govardhana Math, Shringeri Math, Sharda Peeth), one of the four Vedas (Atharva, Rig, Yajur, Sama), one of the four Mahavakyas ('Ayam ātmā Brahma,' 'Prajñānaṃ Brahma,' 'Ahaṃ Brahmāsmi,' 'Tat tvam asi'), and one of the four directions. The circuit is called the most complete single pilgrimage a householder can undertake — it is said to wash away the karma of all previous lives and guarantee liberation (moksha) from the cycle of birth and death.",
    temples:[
      {n:"Badrinath (Badrī Nārāyaṇa)",loc:"Chamoli, Uttarakhand — 3,133m altitude, 301km from Rishikesh",note:"North Dham · Atharva Veda · Mahavakya: 'Ayam ātmā Brahma' · Jyotirmath (Shankaracharya's northern monastery) · Vishnu meditates in the form of a black stone Shaligrama installed by Shankaracharya himself · Flanked by Nar (human) and Narayana (divine) peaks · Brahma Kapal ghat: perform pitru (ancestor) shraddha here — believed to liberate ancestors instantly · Tapt Kund hot spring: mandatory bath at 45°C before darshan · Mata Murti temple: Vishnu's mother at a bend in Alaknanda · Open May–November · The silence of the high Himalayas around this temple is itself a teaching"},
      {n:"Jagannāth (Purushottama)",loc:"Puri, Odisha — Bay of Bengal coast",note:"East Dham · Rig Veda · Mahavakya: 'Prajñānaṃ Brahma' · Govardhana Math (Shankaracharya's eastern monastery) · The three wooden idols — Jagannath, Balabhadra, Subhadra — have no hands or feet, representing the formless absolute beyond anthropomorphism · Rath Yatra (June/July): the three deities ride giant chariots through the city — 10 lakh pilgrims · Non-Hindus cannot enter · The 'Mahaprasad' of Jagannath is cooked in 750 pots in the world's largest temple kitchen — 56 dishes offered daily · The Sudarshan chakra on top rotates against the wind — observed by pilgrims daily"},
      {n:"Rāmanathaswamy",loc:"Rameswaram Island, Tamil Nadu — Indian Ocean",note:"South Dham · Yajur Veda · Mahavakya: 'Ahaṃ Brahmāsmi' · Also the 11th Jyotirlinga · Shringeri Math connection · Rama installed the Shiva linga here to expiate the Brahmahatya (sin of killing Ravana, a Brahmin) on Vibhishana's advice — unique instance of Vishnu's avatar worshipping Shiva, reconciling Shaiva and Vaishnava traditions · Longest temple corridor in the world: 1,220m with 1,212 columns · 22 sacred teerthams (wells): priests pour water from each sequentially over pilgrims — allow 2–3 hours · Pamban Bridge (1914) to the mainland · Adam's Bridge (Ram Setu) ruins visible from Dhanushkodi tip · Agni Teertham at sunrise: bathe in the sea where Agni (fire) is said to dwell · Dhanushkodi ghost town: Ram's army crossed here"},
      {n:"Dwarkadhish (Dvārakādhīsha)",loc:"Dwarka, Saurashtra, Gujarat — Arabian Sea",note:"West Dham · Sama Veda · Mahavakya: 'Tat tvam asi' · Sharda Peeth (Shankaracharya's western monastery, now in Pakistan — surrogate at Dwarka) · Krishna ruled Dwarka for 100 years before the Mahabharata war, then submerged it himself before departing · 5-story, 72-pillar temple with 43m spire visible from the sea · The Dwarka Sharada Peeth: Shankaracharya defeated Mandana Mishra's wife Ubhaya Bharati here in debate — establishing Advaita Vedanta as the supreme philosophy · Gomti River sacred bath before temple entry · Bet Dwarka island (30km): Krishna's actual residence — ferry crossing is itself a pilgrimage · Nageshwar Jyotirlinga is 17km from Dwarka — visit on same day"},
    ],
    pacing:[
      {days:35,label:"Complete Yatra — Clockwise Circuit",desc:"The traditional 35-day circuit follows the clockwise (pradakshina) direction: Begin at Badrinath (North, May–June or Sept–Oct), then Jagannath Puri (East), then Rameswaram (South), close at Dwarka (West). This clockwise direction — moving sun-wise — is considered the auspicious direction for completing a sacred circumambulation of India. Week 1: Badrinath (fly Delhi → Dehradun → drive to Joshimath → Badrinath, 4 days at Badrinath + Hemkund, Mana village, Valley of Flowers). Week 2: Puri by flight (Dehradun → Delhi → Bhubaneswar → Puri), 4–5 days (Jagannath, Konark Sun Temple, Chilika Lake). Weeks 3–4: Rameswaram (flight Chennai, 4 days — Rameswaram, Dhanushkodi, Madurai nearby). Week 5: Dwarka (flight Mumbai, 3 days — Dwarka, Bet Dwarka, Nageshwar). Budget ₹80,000–₹1.5 lakh."},
      {days:21,label:"Immersive 4-Dham Journey",desc:"21 days gives 4–5 days at each Dham for ritual completeness. Badrinath: 5 days — morning puja, Brahmakund bath, Mana village (last Indian village), Satopanth Lake trek. Puri: 5 days — Rath Yatra season if possible, attend all 56-dish bhog times, Puri beach sunrise, Konark. Rameswaram: 5 days — all 22 teerthams on arrival day, lingabhishekam early morning, Dhanushkodi trip, day at Madurai. Dwarka: 4 days — Dwarkadhish, Nageshwar, Bet Dwarka, sunset at Gomti. Budget ₹60,000–₹1 lakh."},
      {days:14,label:"Essential Dham — Focused Darshan",desc:"14 days, 3 days per Dham. Sufficient for the most essential rituals at each site. Badrinath: Tapt Kund bath + main darshan + Brahma Kapal shraddha. Puri: Jagannath main darshan + Mahaprasad + Konark. Rameswaram: Agni Teertham bath + 22 teerthams + sanctum + Dhanushkodi. Dwarka: Dwarkadhish + Bet Dwarka + Nageshwar. Use flights between locations to save time. Best for working pilgrims who cannot take a month off. Budget ₹40,000–₹70,000. Ideal months: September–October (Badrinath still open, Puri and South comfortable, monsoon ending)."},
    ],
    season:"May–June: Badrinath opens (Kapat Utsav, usually late April/early May) — optimal window before monsoon · October–November: Badrinath closing season (Kapat Closing) — emotional and very sacred · November–March: Puri, Rameswaram, Dwarka (South and West India) optimal · Rath Yatra (June/July, Puri): the most sacred Puri time — months in advance planning needed · Avoid: Badrinath in August (peak monsoon, landslides), Puri in peak summer (April–May, extreme heat)",
    bestFor:"Householders and families seeking moksha (liberation) · Those completing a lifetime pilgrimage · Shankaracharya tradition followers and Advaita Vedanta seekers · Pilgrims who want to experience all four directional deities of Bhārata · Those performing pitru shraddha (ancestor rites) at Brahmakund, Badrinath · Devotees of Vishnu in his varied forms — meditating, dancing, protective, royal · Anyone seeking to understand the complete sacred geography of India in a single journey",
    tips:[
      "Begin at Badrinath on Kapat Utsav (opening day of the season, late April/early May) if possible — the first abhishekam of the year after 6 months of closure is performed in the presence of priests and a few thousand pilgrims. The emotion in the air is palpable — people weep at the first sight of the idol.",
      "Brahma Kapal at Badrinath: this flat riverside ghat is believed to be where even Brahma performed shraddha. Hindus perform their ancestral rites (pind dan) here with the belief that it grants instant liberation to departed souls. If you have lost parents or ancestors, make time for this ritual — arrange a pandit the evening before.",
      "Rameswaram: the 22 teerthams ritual requires you to stand still while a priest pours water from each tirtham over you in sequence. Wear clothes you don't mind getting completely drenched. Allow 2.5 hours. After the final tirtham (Kotiteertham), proceed directly to the inner sanctum — you enter 'washed clean' in a literal and spiritual sense.",
      "Puri Jagannath: non-Hindus cannot enter the temple. The solution: climb to the rooftop of the Raghunandan Library across the street — from there you can see the Sudarshana Chakra spinning on the summit. Also: the Mahaprasad (56-dish offering) is available for purchase by all in the outer marketplace — this is considered the most sacred food on earth and equalizes all who eat it.",
      "Rath Yatra at Puri: book accommodation 6 months ahead. The three chariots (Nandighosa, Taladhwaja, Darpadalana) take 2–3 hours to build. They weigh thousands of tons and are pulled by thousands of devotees with thick ropes. To pull the rope even once is considered equivalent to performing 100 Ashwamedha yagnas. Arrive the night before and sleep in the panda area near the Gundicha temple.",
      "Dwarka Bet Dwarka ferry: the ferry is a 30-minute boat ride on the Arabian Sea. On the island, the atmosphere is more intimate than the main Dwarkadhish temple — smaller, quieter, more ancient. The Ranchhod Rai temple here has the original 2,500-year-old black stone idol. Sit on the roof at sunset and watch Dwarka's lights appear across the sea, as Krishna once watched from here.",
      "The four Vedas and four Mahavakyas of Shankaracharya: before the circuit, study one Mahavakya for each Dham. 'Ayam ātmā Brahma' (This self is Brahman — Mandukya Upanishad) for Badrinath. 'Prajñānaṃ Brahma' (Consciousness is Brahman — Aitareya Upanishad) for Puri. 'Ahaṃ Brahmāsmi' (I am Brahman — Brihadaranyaka Upanishad) for Rameswaram. 'Tat tvam asi' (Thou art That — Chandogya Upanishad) for Dwarka. Contemplate the assigned Mahavakya at each Dham for maximum depth.",
      "Completing the Char Dham grants moksha according to tradition. At your final Dham, perform a formal completion ritual — offer flowers at the sanctum, sit in the outer courtyard, and write in a diary or speak aloud what the circuit has meant to you. This act of witness and gratitude seals the pilgrimage in your consciousness.",
      "Tapt Kund, Badrinath: the hot spring at 43–45°C beside the Alaknanda River. Bathing before dawn darshan is mandatory by tradition. Local priests say the spring never loses its temperature regardless of snowfall or season — it has been flowing since Shankaracharya's time. The contrast of bathing in hot spring water with snow on the peaks above is uniquely Himalayan.",
      "The combined circuit — visiting all Jyotirlingas and Char Dham together — is called the Saptapuri-Dham-Jyotirlinga Maha Yatra and is considered the highest single pilgrimage achievement in the Shaiva-Vaishnava tradition. Very few complete it in a lifetime — but to complete even Char Dham alone is a watershed moment in a spiritual life.",
    ],
    stotram:"Badaryāśhrama vāsī tvaṃ Viṣhṇo purīpate\nDvārakādhīśha namaste Rāmanāthāya te namaḥ\nJagannātha svāmī nayana patha gāmī bhava tume\nCaturdhāma parikramā phalam yaḥ paṭhet nityaśhaḥ\nSarvapāpa vinirmuktaḥ Viṣhṇuloke mahīyate\nĀdi Śhaṅkarācārya pranītaṃ dharma saṃsthāpanāya\nCatvāri dhāmāni namāmaḥ — mokṣha pradāyakāni"},
];

// ── Geographic coordinates for pilgrimage route map ──
// [x, y] in SVG viewBox (0 0 210 265) where x=(lon-68)*7, y=(37-lat)*8
export const CIRCUIT_COORDS = {
  jyotirlingas: [
    [17,129,"Somnath"],[8,118,"Nageshwar"],[38,136,"Tryambakeshwar"],[38,143,"Bhimashankar"],
    [50,136,"Grishneshwar"],[57,119,"Omkareshwar"],[55,110,"Mahakaleshwar"],
    [78,50,"Kedarnath"],[105,94,"Kashi"],[131,100,"Vaidyanath"],
    [76,167,"Mallikarjuna"],[79,221,"Rameswaram"],
  ],
  shakti_peethas: [
    [14,72,"Mansa Devi"],[8,80,"Jwala Devi"],[46,136,"Kolhapur"],
    [109,88,"Varanasi"],[140,124,"Tarapith"],[140,117,"Dakshineswar"],
    [160,91,"Kamakhya"],[8,167,"Kanyakumari"],[14,96,"Naina Devi"],
    [60,80,"Vaishnodevi"],[84,192,"Chennai"],[60,136,"Tulja Bhavani"],
  ],
  divya_desams: [
    [82,159,"Tirumala"],[75,182,"Srirangam"],[78,50,"Badrinath"],[8,136,"Dwarka"],
    [84,185,"Kanchipuram"],[75,200,"Kumbakonam"],[72,196,"Thanjavur"],
    [84,192,"Chennai"],[79,221,"Rameswaram"],[70,229,"Kanyakumari"],
    [56,216,"Thiruvananthapuram"],[49,208,"Guruvayur"],[62,200,"Madurai"],
    [77,188,"Tirupati"],[98,168,"Srisailam"],[105,94,"Mathura"],
    [90,157,"Ahobilam"],[47,179,"Mangalore"],[55,110,"Ujjain"],
    [82,66,"Haridwar"],
  ],
  char_dham: [
    [73,48,"Yamunotri"],[76,49,"Gangotri"],[78,50,"Kedarnath"],[81,50,"Badrinath"],
  ],
};
